---
version: 2
defaults: &defaults
  working_directory: /home/circleci/rustmq
  machine:
    image: ubuntu-1604:201903-01
workflows:
  version: 2
  test_on_multiple_targets:
    jobs:
      - checkout
      - format:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - document:
          requires:
            - checkout
      - test-arch64:
          requires:
            - format
            - lint
            - document
      - test-release-arch64:
          requires:
            - format
            - lint
            - document
      - install-arch64:
          requires:
            - test-arch64
            - test-release-arch64
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root:  .
          paths: .
  format:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make fmt-arch64
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make lint-arch64
  document:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make doc-all-arch64
  test-arch64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test-arch64
  test-ubuntu64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test-ubuntu64
  test-release-arch64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test-release-arch64
  test-release-ubuntu64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test-release-ubuntu64
  run-arch64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make run-arch64
  run-ubuntu64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make run-ubuntu64
  install-arch64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make install-arch64
  install-ubuntu64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make install-ubuntu64
